EmergeTools/hackernews

- .github/workflows/android_emerge_upload.yml
Updates to upload the perf bundle, which will package our new custom tests from #14.
> Update upload workflow to upload performance bundle

- android/app/build.gradle.kts
- android/app/src/main/java/com/emergetools/hackernews/data/Dates.kt
- android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsBaseDataSource.kt
- android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsSearchClient.kt
- android/app/src/main/java/com/emergetools/hackernews/data/ItemRepository.kt
- android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt
- android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesScreen.kt
- android/gradle/libs.versions.toml
In this diff I ticked off a couple of feed features, namely:
- Pull to Refresh
- Showing Relative Timestamp
- Properly Canceling in-flight Requests
> Various Feed Improvements

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/gradle/libs.versions.toml
Might need to setup auto-upload of ProGuard/R8 Mapping.
> Initial Sentry Config

- android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt
- android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesScreen.kt
- android/app/src/main/java/com/emergetools/hackernews/ui/theme/Color.kt
- android/app/src/main/java/com/emergetools/hackernews/ui/theme/Theme.kt
Changed the color for the clock icon
Playing with touch target size for actions
> Touch Target + Color Tweaks

- android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt
- android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt
Added the ability to toggle the post body size, defaulting to collapsed and displaying 4 lines.
> Post Body Size Toggling

- android/app/build.gradle.kts
- android/app/src/main/java/com/emergetools/hackernews/data/remote/HackerNewsBaseApi.kt
- android/app/src/main/java/com/emergetools/hackernews/data/remote/HackerNewsBaseClient.kt
- android/app/src/main/java/com/emergetools/hackernews/features/login/LoginScreen.kt
- android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt
- android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesScreen.kt
- android/gradle/libs.versions.toml
I updated the Feed Header design to look nicer and work better with more feeds. I'm using saket's squiggly span decoration because its fun but also fits the theme nicely.
Then I just added more feeds like best, show, and ask. I might also add jobs.
> Adding More Feed Types

- android/app/build.gradle.kts
- android/app/src/main/java/com/emergetools/hackernews/HackerNewsApplication.kt
This update includes adding new feeds as well as fixing a crash on startup.
> Beta Release 2

- android/app/src/main/java/com/emergetools/hackernews/features/bookmarks/BookmarksScreen.kt
This PR just adds an empty state with some education on how to bookmark stories. I'll update it once we change the "unbookmark" behavior a bit.
> Adding an empty state for the Bookmarks Screen

- android/app/build.gradle.kts
Removed the composeOptions block and added a top level composeCompiler configuration block.
> Remove composeOptions block

- android/app/build.gradle.kts
Just creating a release build and publishing to our beta tracks
> bump version to 1.0-beta03

- android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt
Fixes #135
| Before | After |
|-------|-------|
| https://github.com/user-attachments/assets/e4abf7d4-194a-447d-a424-6d460080fd62 | https://github.com/user-attachments/assets/df24a91f-593f-46a2-b494-77e2081af485 |
> Fixes #135 - Add ISO date time parser to comment date

- .github/workflows/android_release_build.yml
Also:
- Produce a universal APK
- Upload that APK to the build artifacts
- If this is a release add that APK to the release also
This resolves #140. Thanks to bartekpacia@ for the initial commit.
> Build Android release whenever the app changes

- ios/HackerNews.xcodeproj/project.pbxproj
- ios/HackerNews/Components/StoryRow.swift
- ios/HackerNews/Components/StoryRowV2.swift
- ios/HackerNews/ContentView.swift
- ios/HackerNews/Models/AppViewModel.swift
- ios/HackerNews/Network/HNApi.swift
- ios/HackerNews/Screens/BookmarksScreen.swift
- ios/HackerNews/Screens/FeedPagerTest.swift
- ios/HackerNews/Screens/FullScreentest.swift
- ios/HackerNews/Screens/LoginScreen.swift
- ios/HackerNews/Screens/PostListScreen.swift
- ios/HackerNews/Screens/SettingsScreen.swift
- ios/HackerNewsTests/SwiftSnapshotTest.swift
Adding more Feed Types. For some reason I'm having trouble with Jobs so omitting that for now.
> Adding More Feeds

- ios/HackerNews.xcodeproj/project.pbxproj
- ios/HackerNews/Components/CommentRow.swift
- ios/HackerNews/Components/CommentsHeader.swift
- ios/HackerNews/Models/StoryViewModel.swift
- ios/HackerNews/Network/HNApi.swift
- ios/HackerNews/Screens/PostListScreen.swift
- ios/HackerNews/Screens/StoryScreen.swift
A first pass at updating the comments feature, adding the new comment row design, and adding the comment row header.
> Updating Comment Row

- android/app/build.gradle.kts
This will unblock a lot of updates.
> Upgrade compile/target sdk to 35

- ios/HackerNews/AppViewModel.swift
- ios/HackerNews/Comments/CommentRow.swift
- ios/HackerNews/Comments/CommentsHeader.swift
- ios/HackerNews/Comments/CommentsScreen.swift
- ios/HackerNews/Feed/FeedScreen.swift
- ios/HackerNews/Utils/UINavigationController+SwipeBack.swift
- adds a content preview if you long press
- adds a nice animation when collapsing/expanding comments
- adds swipe navigation to CommentScreen
- strip HTML from the post text
- fix comments clipping at the bottom
- fix crash
> Beta feedback

- ios/HackerNews.xcodeproj/project.pbxproj
- ios/HackerNews.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios/HackerNews/HNApp.swift
- ios/HackerNews/Settings/SendFeedbackScreen.swift
- ios/HackerNews/Settings/SettingsScreen.swift
Uses Sentry's user feedback feature which lets us consolidate our feedback.
> Add feedback form

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/build.gradle.kts
- android/gradle/libs.versions.toml
This reverts commit 314b0748ee9621c819bb9832cb78752cd85c9bf9.
> Re-add Sentry

- android/app/src/main/java/com/emergetools/hackernews/features/bookmarks/BookmarksDomain.kt
- android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt
- android/app/src/main/java/com/emergetools/hackernews/ui/components/StoryRow.kt
Fixes
[HACKERNEWS-ANDROID-H](https://emerge-tools.sentry.io/issues/5799728222/?project=4506028523388928&query=is%3Aunresolved%20issue.category%3A%5Berror%2Coutage%5D&referrer=issue-stream&stream_index=6)
> Fix NPE when title is null.

- ios/HackerNews.xcodeproj/project.pbxproj
Bumps iOS version to 3.10 for the next release
> Bump iOS version to 3.10
