EmergeTools/hackernews

android/app/src/main/AndroidManifest.xml
Previously we got the following log message:
> Task :app:processDebugMainManifest
package="com.emergetools.hackernews" found in source AndroidManifest.xml: /Users/chromy/src/hackernews/android/app/src/main/AndroidManifest.xml. Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored. Recommendation: remove package="com.emergetools.hackernews" from the source AndroidManifest.xml: /Users/chromy/src/hackernews/android/app/src/main/AndroidManifest.xml.
=> Remove AndroidManifest.xml package

android/app/proguard-rules.pro
Seems like we are stripping something important which is causing a soft error (loader spins forever).
Something in the rules below seems to resolve it (although maybe we should move to R8?).
See:
- https://square.github.io/retrofit/
- https://square.github.io/okhttp/features/r8_proguard/
Specifically I added these rules:
- https://github.com/square/retrofit/blob/trunk/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro
- https://raw.githubusercontent.com/square/okhttp/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro
- https://github.com/square/okio/blob/c90794f83170d770eb247c56ade80c0a6661a5d6/android-test/multidex-config.pro
=> Additional Proguard rules

android/app/src/main/java/com/emergetools/HackerNewsApplication.kt, android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsBaseClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsBaseDataSource.kt, android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsSearchClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/ItemRepository.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesRouting.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesScreen.kt
> This is an idea I have to load the feed lazily given the current infrastructure.
> 
> When we request a feed, we have a list of ID's, so we can populate our LazyList with a bunch of Loading State items.
> 
> Whenever I Loading State item comes into the Composition, it launches a `SideEffect` which will call up to the ViewModel to fetch that item. This seems like a decent approach without having to explicitly manage a paging mechanism in the ViewModel.
After second thought, I think the better approach is paging. And since we don't have actual paging via the API, we can simulate it.
Created a simple repository layer which wraps the actual base client, and adds the ability to request pages.
The requests are still sequential, but that can be updated later to be a series of async requests. …
=> Feed Loading Strategy

android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsSearchClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/ItemRepository.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt
Just making the comment screen more feature complete:
- Rendering post content if it has any
- Initial loading state
- Relative timestamps
=> Comment Feature Updates

android/app/src/main/java/com/emergetools/hackernews/AppActivity.kt, android/app/src/main/java/com/emergetools/hackernews/AppDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/HtmlToAnnotatedString.kt, android/app/src/main/java/com/emergetools/hackernews/features/settings/SettingsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoryScreen.kt, android/app/src/main/java/com/emergetools/hackernews/ui/theme/Color.kt, android/app/src/main/java/com/emergetools/hackernews/ui/theme/Theme.kt, android/app/src/main/java/com/emergetools/hackernews/ui/theme/Type.kt
This PR is just updating and organizing our Previews for Screens and Components. The ideas is that every component has multiple previews for different visual states and also different logical states.
Part of the Goal is is to create a `MultiPreview` annotation that we can just tack on to all future previews with all the desired test states.
=> Updating Previews for Snapshot Baseline

android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsWebClient.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/login/LoginScreen.kt
This builds on the previously added login functionality to be able to like comments.
This mostly gets the wiring in place, it is not the final state of the UI, and we still need to think about how eager state updates will work (essentially updating a tree as our backing state).
=> Initial Pass at Liking Comments

android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsBaseDataSource.kt, android/app/src/main/java/com/emergetools/hackernews/data/ItemRepository.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/settings/SettingsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt
Apparently there is a chance that the API just straight up returns null as a valid response. In this scenario our JsonDeserializer fails and crashes the app. And in the case that this value is in the first page of the feed, we will constantly crash on startup.
In order to safeguard against this, I just created a wrapper type and a custom deserializer that just checks if a gauranteed property exists in the json response, and if it does, use the normal item deserializer, otherwise map it to an empty object that is mostly a marker type, we can just ignore it.
=> Fixing a crash when loading Feeds

android/app/src/main/java/com/emergetools/hackernews/AppActivity.kt, android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsBaseDataSource.kt, android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsWebClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/LocalCookieJar.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsRouting.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/HtmlToAnnotatedString.kt
This PR is our initial pass at setting up comments (top level comments, not replies yet)
Added a minimal UI for submitting comments
Modified the `CommentsDomain` with new state and actions for updating / submitting comments
Extracted out Form Data neccesary for submitting comments
Added a post request to the comment endpoint to tie it all together
=> Posting Comments

android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsWebClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/ItemRepository.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt
Previously we were loading the comment tree by using the `search` api. This was nice but there are a few drawbacks:
- When adding a comment, there is some delay before the comment shows up in the response. This means we would have to juggle some local state, or just treat it as a fire and forget request.
- If we like a comment, updating the backing comment tree is a bit more complex then, say, updating a list of comments.
Since we were already scraping the comments page for upvote links for each comment, I figured we could try just using the comments page as our data source for comments. The results were fairly good, a simplified model of comments, and immediate updated when we post a top-level comment.
This does get rid of the parent-child relationship between comments, which probably …
=> A new comment loading approach

android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsSearchClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/HackerNewsWebClient.kt, android/app/src/main/java/com/emergetools/hackernews/data/ItemRepository.kt, android/app/src/main/java/com/emergetools/hackernews/features/comments/CommentsDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/login/LoginDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesDomain.kt, android/app/src/main/java/com/emergetools/hackernews/features/stories/StoriesScreen.kt
In order to make sure that app doesn't just crash constantly, we need to have some basic error handling in place.
The goal of this diff is to have a very simple solution for most cases. For the feed, we can show an error item that allows you to try request the feed again.
I'd love to have a bit more sophistication here, but this is a good first step. At the very least if they lose internet connection the app won't crash.
=> Simple Feed Error Handling

android/.gitignore, android/app/build.gradle.kts
Runs sentry setup wizard and configures project.
Also moves emerge block out of android block
=> Fix sentry for release, move emerge block out of Android block

android/app/src/main/java/com/emergetools/hackernews/features/settings/SettingsScreen.kt
As per the Play Store policies, apparently we need an in-app link to the Privacy Policy.
=> Added a Privacy Policy link in app

android/app/src/main/java/com/emergetools/hackernews/features/settings/SettingsScreen.kt, android/app/src/main/java/com/emergetools/hackernews/ui/preview/AppStoreSnapshot.kt
Showcasing fixing our small screen bug in settings by leveraging Previews + Snapshots.
=> Small Screen Preview Fix

android/app/src/main/java/com/emergetools/hackernews/data/remote/HackerNewsWebClient.kt
Fixes a crash when navigating to CommentsScreen due to incorrect parsing of timestamp. The returned timestamp withing HTML also contains millis which causes the parsing to fail.
Actual: 2024-11-03T04:53:41 1730609621
Expected: 2024-11-03T04:53:41
This diff simply strips the millis and only uses timestamp to parse the date.
1. Navigate to Comments screen for any post
2. Notice that the app crashes without the change
<details><summary>Stacktrace</summary>
<code>
```
FATAL EXCEPTION: main (Ask Gemini)
Process: com.emergetools.hackernews.debug, PID: 4649
java.time.format.DateTimeParseException: Text '2024-11-02T20:55:10 1730580910' could not be parsed, unparsed text found at index 19
at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2053)
at …
```
=> Fix crash in CommentsScreen due to incorrect timestamp parsing

ios/HackerNews.xcodeproj/project.pbxproj, ios/HackerNews.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/HackerNews/Assets.xcassets/Color.colorset/Contents.json, ios/HackerNews/Assets.xcassets/HNRed.colorset/Contents.json, ios/HackerNews/Components/StoryRowV2.swift, ios/HackerNews/Screens/BookmarksScreen.swift, ios/HackerNews/Screens/PostListScreen.swift, ios/HackerNews/Screens/SettingsScreen.swift, ios/HackerNews/Screens/StoriesScreen.swift, ios/HackerNews/Screens/StoryRow.swift, ios/HackerNews/Utils/Colors.swift
This is just simply updating the design of the Story Row to match what it looks like on Android. Also just getting back my SwiftUI chops a bit.
=> Redesign Story Row

ios/HackerNews.xcodeproj/project.pbxproj, ios/HackerNews/Components/StoryRow.swift, ios/HackerNews/ContentView.swift, ios/HackerNews/Models/AppViewModel.swift, ios/HackerNews/Network/HNApi.swift, ios/HackerNews/Screens/LoginScreen.swift, ios/HackerNews/Screens/PostListScreen.swift, ios/HackerNews/Utils/Pager.swift, ios/HackerNewsTests/SwiftSnapshotTest.swift
I built a simple system similar to Android to support paging. We get the full list of Ids for a feed, and just feed it into a lil helper struct that will chunk it into pages we can request. Once a page is loaded fully we return the page of items.
The mechanism for paging is a "marker view" that triggers the viewmodel to load the next page.
=> Adding Paging for Feeds

ios/HackerNews.xcodeproj/project.pbxproj, ios/HackerNews/Components/CommentRow.swift, ios/HackerNews/Models/StoryViewModel.swift, ios/HackerNews/Network/HNWebClient.swift, ios/HackerNews/Screens/StoryScreen.swift, ios/HackerNews/Utils/DateUtils.swift, ios/HackerNews/Utils/Previews.swift
This diff creates the initial infrastructure needed to scrape the Hacker News website.
Using this to grab the comments and replace our comment loading with comments scraped from the story page.
=> Scraping Comments

ios/HackerNews/ContentView.swift, ios/HackerNews/HNApp.swift, ios/HackerNews/Models/AppViewModel.swift, ios/HackerNews/Models/StoryViewModel.swift, ios/HackerNews/Network/HNWebClient.swift, ios/HackerNews/Screens/LoginScreen.swift, ios/HackerNews/Screens/SettingsScreen.swift
Removed old Login Setup, and added some new stuff:
- Basic Login Sheet
- Login Endpoint that sends a Post Request and stores the auth cookie
- Simple Settings Page with an entrypoint to Login
=> Login + Cookie Management

ios/HackerNews/Stories/StoryRow.swift
- Ensure the whole `StoryRow` is tappable, instead of only allowing the user to tap on the frame of its subviews
- Only able to tap on the subviews of the `StoryRow`, many tap misses, creating a sense of unresponsiveness to the interaction
https://github.com/user-attachments/assets/1f9b9dab-e524-4969-8ad7-184d6f713c7e
- The whole `StoryRow` is tappable
https://github.com/user-attachments/assets/0261d166-7056-4c82-b7d4-79bcbfc3c6db
=> [iOS][UI] Improve StoryRow tappable area

ios/HackerNews/Auth/LoginScreen.swift
Added button to open Hacker New's Guidelines
=> Add Hacker News guidelines button to login screen

android/app/build.gradle.kts, android/app/schemas/com.emergetools.hackernews.data.local.HackerNewsDatabase/1.json, android/build.gradle.kts, android/gradle.properties, android/gradle/libs.versions.toml
This will generate the database schema in a build caching compatible way.
This also generates the database code in Kotlin to save java
compilation.
Clean up buildscript classpath.
Remove deprecated flag which is now enabled by default.
=> Apply room gradle plugin

android/build.gradle.kts
This should fix the integration test errors like this one: https://github.com/EmergeTools/emerge-android/actions/runs/13502089290/job/37722785622?pr=471#step:6:44
=> Remove Emerge Plugin application

ios/HackerNews.xcodeproj/project.pbxproj, ios/HackerNews.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/HackerNews/HNApp.swift
Enable the appHangTrackingV2 and update Sentry from 8.49.0 to 8.50.1.
AppHangsV2 is more powerful and it would be great to see some data coming in from the Hackernews app. For more info see: https://docs.sentry.io/platforms/apple/guides/ios/configuration/app-hangs/#app-hangs-v2.
=> chore: Enable Sentry appHangTracking V2

ios/HackerNews/Feed/FeedScreen.swift
This is to better accommodate weird spacing issues with 85% text size on specific devices. 
Before:
After:
=> Adjust spacing in the Feed header

ios/HackerNews/Web/WebView.swift
Allows user to share the link of the web view directly.
=> Add share button to Web View menu

android/settings.gradle.kts
Configuration copied from here: https://central.sonatype.org/publish/publish-portal-snapshots/#consuming-via-maven
=> Consume snapshots from new url.

android/app/build.gradle.kts
This should get us logs via logcat https://docs.sentry.io/platforms/android/integrations/logcat/#support-with-sentry-logs
=> Bump sentry sdk version to latest
